### ISSUE TITLE
cannot build on windows

### ISSUE THREAD

**Issue by fdncred** [fennewald/nu_plugin_net#1]
I cannot build it on Windows. I get this error message.
```
  = note: LINK : fatal error LNK1181: cannot open input file 'Packet.lib'
```

**Comment by fennewald** [comment]
Looks like this is known behavior for pnet, the underlying library used for networking. https://github.com/libpnet/libpnet/issues/278

I'll update the readme with instructions for building on windows.

**Comment by fennewald** [comment]
In light of the added difficulties, I'll test if building on a machine with those steps complete produces binaries which work on machines w/o them. If it does, I'll post binaries on this repo!

Unsure what is possible very much a windows noob.

**Comment by fdncred** [comment]
just let me know and i can test it on windows pretty easily

**Comment by fdncred** [comment]
yup, I got it to build finally. I made some changes to it and make a fork of it in my repo. I hope you don't mind. Good work! Here's mine if you want to take a peak. https://github.com/fdncred/nu_plugin_pnet
