### ISSUE TITLE
load failed in 0.94.2

### ISSUE THREAD

**Issue by kurokirasama** [fennewald/nu_plugin_net#18]
```nu
plugin add ~/.cargo/bin/nu_plugin_net
```
gives
```
Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: Plugin `net` is compiled for nushell version 0.93.0, which is not
  │ compatible with version 0.94.2
```

I installed it with cargo.

**Comment by fennewald** [comment]
Just updated to 0.93.0, probably should've checked for newer versions. Will fix this right now.

**Comment by fennewald** [comment]
Just ran `cargo publish`, so it may take a few minutes to show up in their repos, but you should be all good to go.

**Comment by kurokirasama** [comment]
i got it already, thanks!
