### ISSUE TITLE
error in nushell 0.97.2

### ISSUE THREAD

**Issue by kurokirasama** [fennewald/nu_plugin_net#24]
Hey, I just updated nushell to 0.97.2 and the plugin to 1.7.0, but when doing `plugin add ~/.cargo/bin/nu_plugin_net` i get this error:

```
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: missing field `description`
```

**Comment by fennewald** [comment]
I tracked this down, it looks like 0.97.2 will come with a breaking change to the plugin interface, `usage` is being renamed to `description`. [Here's the commit](https://github.com/nushell/nushell/commit/95b78eee25a876f425b22ecb05686896c7828a36)

This is super easy to implement on our end, but nu_protocol v0.97.2 is not yet released. Unfortunately, there's nothing we can do to support 0.97.2 until nushell publishes an actual release.

I'll open a PR with what the fix _will_ be, but the fix won't work until nushell publishes the new version.

**Comment by kurokirasama** [comment]
perfect! thanks

**Comment by fennewald** [comment]
Updated version has been pushed
