### ISSUE TITLE
Could you release 1.8.0 on github

### ISSUE THREAD

**Issue by happysalada** [fennewald/nu_plugin_net#28]
Hi, I'm the maintainer of this nushell plugin on nixos.
Thank you so much for making this!
On nixos we rely on building from source, and it looks like 1.8.0 is not tagged on github.
When you have a moment if you could tag it, I could update this in nixpkgs.
Thanks again for making this!

**Comment by fennewald** [comment]
Of course! Thank you for the kind words. Sorry I forget to tag it. Should be tagged and pushed now.
