### ISSUE TITLE
no more capnp in nushell

### ISSUE THREAD

**Issue by kurokirasama** [fennewald/nu_plugin_net#4]
Hey!! Latest version of nushell doesn't have `capnp` anymore.Only json, and msgpack, so I'm getting that error when starting nushell

**Comment by amtoine** [comment]
i cannot even run the register command...

i freezes as soon as i type the last "t" in
```bash
register /path/to/nu_plugin_net
```

**Comment by fennewald** [comment]
this issue is stale, it's been moved over to json
